# Generated by Django 4.1.5 on 2023-01-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='Lanzamiento'),
        ),
    ]
