# Generated by Django 4.1.5 on 2023-01-27 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
        ('reader', '0002_lend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_lend', to='book.book', verbose_name='Libro'),
        ),
    ]
