# Generated by Django 4.1.5 on 2023-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_lend_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
